# docker-compose-client.yml
version: '3.8'
services:
  client:
    image: "${DOCKER_USERNAME}/zkp_client:latest"
    container_name: zkp-client
    networks:
      - zkp_network

networks:
  zkp_network:
    external: true
