version: '3.8'

services:
  client:
    image: ${{ secrets.DOCKER_USERNAME }}/zkp_client:latest
    container_name: zkp_client
    networks:
      - zkp_network

networks:
  zkp_network:
    external: true
