version: '3.8'

services:
  server:
    image: ${{ secrets.DOCKER_USERNAME }}/zkp_server:latest
    container_name: zkp_server
    ports:
      - "50051:50051"
    networks:
      - zkp_network

networks:
  zkp_network:
    external: true
