version: '3.8'

services:
  server:
    image: zkp_server
    container_name: zkp_server
    build:
      context: .
      dockerfile: Dockerfile  # Build from the server Dockerfile
    ports:
      - "50051:50051"
    networks:
      - zkp_network

networks:
  zkp_network:
    external: true 
